"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isValidGmail = exports.normalizeGmail = exports.logout = exports.loginOrCreateUser = exports.getAccountByGmail = exports.getCurrentUser = void 0;
var localStorage_1 = require("./localStorage");
Object.defineProperty(exports, "getCurrentUser", { enumerable: true, get: function () { return localStorage_1.getCurrentUser; } });
Object.defineProperty(exports, "getAccountByGmail", { enumerable: true, get: function () { return localStorage_1.getAccountByGmail; } });
Object.defineProperty(exports, "loginOrCreateUser", { enumerable: true, get: function () { return localStorage_1.loginOrCreateUser; } });
Object.defineProperty(exports, "logout", { enumerable: true, get: function () { return localStorage_1.logout; } });
Object.defineProperty(exports, "normalizeGmail", { enumerable: true, get: function () { return localStorage_1.normalizeGmail; } });
Object.defineProperty(exports, "isValidGmail", { enumerable: true, get: function () { return localStorage_1.isValidGmail; } });
