"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteProduct = exports.updateProduct = exports.createProduct = exports.getProductById = exports.getActiveProducts = exports.getProducts = void 0;
var localStorage_1 = require("./localStorage");
Object.defineProperty(exports, "getProducts", { enumerable: true, get: function () { return localStorage_1.getProducts; } });
Object.defineProperty(exports, "getActiveProducts", { enumerable: true, get: function () { return localStorage_1.getActiveProducts; } });
Object.defineProperty(exports, "getProductById", { enumerable: true, get: function () { return localStorage_1.getProductById; } });
Object.defineProperty(exports, "createProduct", { enumerable: true, get: function () { return localStorage_1.createProduct; } });
Object.defineProperty(exports, "updateProduct", { enumerable: true, get: function () { return localStorage_1.updateProduct; } });
Object.defineProperty(exports, "deleteProduct", { enumerable: true, get: function () { return localStorage_1.deleteProduct; } });
