import { ContactForm } from "@/components/ContactForm";
import { Icon } from "@/components/Icon";
import { PageShell } from "@/components/PageShell";

const topics = [["box", "Orders & delivery", "Track, modify, or cancel orders", "24"], ["creditCard", "Payments & KHQR", "Payment issues, refunds, KHQR setup", "18"], ["user", "Account & profile", "Login, addresses, notifications", "12"], ["package", "Products & suppliers", "Quality issues, availability, sourcing", "9"], ["truck", "Delivery zones", "Coverage areas, delivery times", "7"], ["refresh", "Returns & refunds", "Policy, process, timelines", "11"]] as const;
const faqs = [["How do I track my order?", "Go to My Orders and select View on any order to see real-time delivery status and tracking updates."], ["What payment methods are accepted?", "You can pay by KHQR, ABA transfer, Wing, or major debit and credit cards."], ["Can I change or cancel an order?", "Confirmed orders can be changed before supplier fulfilment begins. Contact our support team as soon as possible."], ["What is your return policy?", "Report quality issues within seven days and include a photo so our team can arrange a refund or replacement."], ["Is there a minimum order value?", "There is no minimum order value. Delivery is free on orders over $30."]];

export default function SupportPage() {
  return (
    <PageShell>
      <section className="soft-grid bg-primary-soft py-12 sm:py-16"><div className="container-shell text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-primary text-white"><Icon name="headset" size={26}/></span><h1 className="mt-5 text-4xl font-black tracking-tight">How can we help you?</h1><p className="mt-3 text-muted-ink">Search our help center or browse topics below. Our team is available Mon–Sat, 7AM–9PM.</p><form className="mx-auto mt-7 flex max-w-xl rounded-2xl border border-line bg-white p-2 shadow-sm"><div className="flex min-w-0 flex-1 items-center gap-3 px-3"><Icon name="search" size={18} className="text-muted-ink"/><input placeholder="Search help articles..." className="min-w-0 flex-1 text-sm outline-none"/></div><button className="rounded-xl bg-primary px-6 py-3 text-xs font-bold text-white">Search</button></form><div className="mt-4 flex flex-wrap justify-center gap-2 text-xs"><span className="py-1.5 text-muted-ink">Popular:</span>{["Track order", "KHQR payment", "Return policy", "Delivery zones"].map((item) => <button key={item} className="rounded-full border border-line bg-white px-3 py-1.5">{item}</button>)}</div></div></section>
      <div className="container-shell py-14"><h2 className="text-2xl font-bold">Browse help topics</h2><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{topics.map(([icon, title, detail, count]) => <button key={title} className="surface-card flex items-center gap-4 p-5 text-left hover:border-primary/30 hover:shadow-lg"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-primary-soft text-primary"><Icon name={icon} size={21}/></span><span className="min-w-0 flex-1"><strong className="block">{title}</strong><span className="mt-1 block text-sm text-muted-ink">{detail}</span></span><span className="text-xs text-muted-ink">{count} ›</span></button>)}</div>
        <div className="mt-14 grid gap-8 lg:grid-cols-[2fr_1fr]"><section><h2 className="text-2xl font-bold">Frequently asked questions</h2><div className="mt-5 space-y-3">{faqs.map(([question, answer], index) => <details key={question} open={index === 0} className="group overflow-hidden rounded-2xl border border-line bg-white"><summary className="flex list-none items-center justify-between px-5 py-4 font-semibold marker:hidden">{question}<Icon name="chevronDown" size={17} className="transition group-open:rotate-180"/></summary><p className="border-t border-line bg-[#fafbfa] px-5 py-4 text-sm leading-6 text-muted-ink">{answer}</p></details>)}</div></section><aside><h2 className="text-2xl font-bold">Contact us</h2><div className="mt-5 rounded-[20px] bg-primary p-5 text-white"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-white/15"><Icon name="headset"/></span><div><strong>Live chat</strong><p className="text-xs text-white/70">Online now · ~2 min wait</p></div></div><button className="mt-4 w-full rounded-xl bg-white py-2.5 text-sm font-bold text-primary">Start chat</button></div><div className="my-4 surface-card p-5 text-sm"><strong>Call us</strong><p className="mt-1 text-primary">+855 23 123 456</p><span className="text-xs text-muted-ink">Mon–Sat, 7AM–9PM</span></div><ContactForm/></aside></div>
        <div className="mt-14 flex items-center justify-between rounded-[22px] bg-[#dff8e8] p-6"><div className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-xl bg-primary text-white">⌁</span><div><strong className="block">All systems operational</strong><span className="text-xs text-muted-ink">Website, payments, and tracking are running normally.</span></div></div><button className="hidden text-sm font-semibold text-primary sm:block">View status page →</button></div>
      </div>
    </PageShell>
  );
}
