/* eslint-disable @next/next/no-img-element */
import { Icon } from "@/components/Icon";
import { LoginForm } from "@/components/LoginForm";
import { Logo } from "@/components/Logo";
import { imageUrl } from "@/lib/data";

export default function LoginPage() {
  return <main className="grid min-h-screen lg:grid-cols-2"><section className="relative hidden overflow-hidden bg-primary-dark p-12 text-white lg:flex lg:flex-col lg:justify-between"><img src={imageUrl("lush Cambodian vegetable market produce blue green cinematic", "4:5")} alt="Cambodian food market" className="absolute inset-0 size-full object-cover opacity-35"/><div className="absolute inset-0 bg-gradient-to-br from-[#0a5a34]/80 to-[#0b376f]/80"/><div className="relative"><Logo inverted/></div><div className="relative max-w-xl"><h2 className="text-5xl font-black leading-tight tracking-tight">Cambodia&apos;s freshest food marketplace</h2><p className="mt-5 max-w-lg leading-7 text-white/70">Order from verified local farms and suppliers. Fresh produce, quality meats, and local beverages—delivered next day.</p><ul className="mt-8 space-y-4">{["120+ verified Cambodian suppliers", "Next-day delivery in Phnom Penh", "Pay with KHQR or ABA transfer"].map((item) => <li key={item} className="flex items-center gap-3 text-sm"><span className="grid size-8 place-items-center rounded-lg bg-white text-primary"><Icon name="check" size={16}/></span>{item}</li>)}</ul></div><blockquote className="relative border-t border-white/30 pt-7 text-sm italic text-white/65">“The freshest produce at the best prices—our restaurant relies on SUPPY-MATRIX every week.”<footer className="mt-4 not-italic text-white"><strong>Sopheak Neam</strong><span className="block text-xs text-white/50">Head chef, Malis Restaurant</span></footer></blockquote></section><section className="flex items-center justify-center px-6 py-14 sm:px-12"><div className="absolute left-6 top-6 lg:hidden"><Logo/></div><LoginForm/></section></main>;
}
