"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getActiveProducts, PLATFORM_CHANGED_EVENT, type Product } from "@/lib/localStorage";
import { Icon } from "./Icon";
import { ProductCard } from "./ProductCard";
import { SectionHeader, VerifiedBadge } from "./ui";
import { useMarketplace } from "./MarketplaceProvider";
import { addToCart, startChat } from "@/lib/localStorage";
import { useRouter } from "next/navigation";

const categories=["Food & Beverage","Agriculture","Electronics","Construction Materials","Office Supplies","Packaging Supplies"];
export function HomeExperience(){const [products,setProducts]=useState<Product[]>([]),{requireCustomer,notify}=useMarketplace(),router=useRouter();useEffect(()=>{const sync=()=>setProducts(getActiveProducts().slice(0,4));sync();window.addEventListener(PLATFORM_CHANGED_EVENT,sync);return()=>window.removeEventListener(PLATFORM_CHANGED_EVENT,sync)},[]);const add=(p:Product)=>requireCustomer(c=>{addToCart(c.id,p);notify("Product added to your cart")});const chat=(p:Product)=>requireCustomer(c=>router.push(`/chat?room=${startChat(c,p).id}`));return <>
<section className="overflow-hidden border-b border-line bg-white"><div className="container-shell grid items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div><VerifiedBadge>Verified Cambodian Marketplace</VerifiedBadge><h1 className="mt-6 max-w-3xl text-4xl font-black leading-[1.08] tracking-[-.045em] text-primary sm:text-6xl">Cambodia’s Trusted Supplier Marketplace</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-ink">Buy, sell, and connect with verified Cambodian suppliers through MATRIX SUPPLY Cambodia.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="primary-btn px-6 py-3.5">Browse Marketplace <Icon name="arrowRight" size={16}/></Link><Link href="/login" className="secondary-btn px-6 py-3.5">Become a Supplier</Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold text-slate-500"><span>✓ Phone Verification</span><span>✓ Identity Information</span><span>✓ Local Cambodian Suppliers</span></div></div><MarketplacePreview/></div></section>
<section className="container-shell py-12"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["shield","Verified Suppliers"],["check","Phone Verification"],["user","National ID Provided"],["mapPin","Local Cambodian Marketplace"]].map(([icon,label])=><div key={label} className="card flex items-center gap-3 p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[var(--accent-soft)] text-accent"><Icon name={icon as "shield"}/></span><strong className="text-sm">{label}</strong></div>)}</div></section>
<section id="how-it-works" className="border-y border-line bg-white"><div className="container-shell py-16"><SectionHeader title="A simple, trusted way to trade" description="Built for Cambodian customers and suppliers to connect with confidence."/><div className="grid gap-5 md:grid-cols-3">{[["01","Register securely","Complete phone and identity information for a Verified Account."],["02","Buy or sell products","Browse trusted listings or post products directly as a supplier."],["03","Chat and manage orders","Coordinate order requests and fulfillment in one place."]].map(([n,t,d])=><div key={n} className="card hover-card p-6"><span className="text-xs font-black text-accent">{n}</span><h3 className="mt-5 text-lg font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-ink">{d}</p></div>)}</div></div></section>
<section className="container-shell py-16"><SectionHeader title="Featured categories" description="Find everyday business supplies from verified Cambodian suppliers." action={<Link href="/products" className="text-sm font-bold text-primary">View marketplace →</Link>}/><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{categories.map((x,i)=><Link key={x} href={`/products?category=${encodeURIComponent(x)}`} className="card hover-card p-5"><span className="grid size-10 place-items-center rounded-xl bg-primary-soft text-primary"><Icon name={i%2?"package":"store"}/></span><strong className="mt-5 block text-sm">{x}</strong></Link>)}</div></section>
{products.length>0&&<section className="border-y border-line bg-white"><div className="container-shell py-16"><SectionHeader title="Featured products" description="Active listings from the Trusted Supplier Network."/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map(p=><ProductCard key={p.id} product={p} onAddToCart={add} onRequestQuote={chat} onChat={chat}/>)}</div></div></section>}
<section className="container-shell py-16"><div className="grid overflow-hidden rounded-3xl bg-primary text-white md:grid-cols-2"><div className="border-b border-white/10 p-8 md:border-b-0 md:border-r lg:p-10"><span className="text-xs font-bold uppercase tracking-wider text-emerald-300">For suppliers</span><h2 className="mt-3 text-2xl font-bold">Start selling to customers across Cambodia</h2><p className="mt-3 text-sm leading-6 text-white/70">Create your verified business profile and publish products directly.</p><Link href="/login" className="mt-6 inline-flex rounded-xl bg-white px-5 py-3 text-sm font-bold text-primary">Register as Supplier</Link></div><div className="p-8 lg:p-10"><span className="text-xs font-bold uppercase tracking-wider text-emerald-300">For customers</span><h2 className="mt-3 text-2xl font-bold">Find trusted products from local suppliers</h2><p className="mt-3 text-sm leading-6 text-white/70">Compare products, chat with suppliers, and submit order requests.</p><Link href="/products" className="mt-6 inline-flex rounded-xl border border-white/25 px-5 py-3 text-sm font-bold text-white">Explore Products</Link></div></div></section></>}
function MarketplacePreview(){return <div className="relative mx-auto max-w-lg rounded-[28px] border border-line bg-background p-5 shadow-[0_24px_60px_rgba(17,43,74,.14)]"><div className="flex items-center justify-between border-b border-line pb-4"><div><p className="text-xs font-bold text-primary">Marketplace activity</p><p className="mt-1 text-[11px] text-muted-ink">MATRIX SUPPLY Cambodia</p></div><VerifiedBadge/></div><div className="mt-5 grid grid-cols-[1fr_120px] gap-4"><div className="rounded-2xl bg-white p-4 shadow-sm"><div className="aspect-[5/3] rounded-xl bg-[linear-gradient(135deg,#e7f7f1,#eaf0f7)]"/><VerifiedBadge>Verified Supplier</VerifiedBadge><h3 className="mt-3 text-sm font-bold">Cambodian business supplies</h3><p className="mt-2 text-lg font-black text-primary">$24.00</p></div><div className="space-y-3"><div className="rounded-2xl bg-white p-3 shadow-sm"><Icon name="cart" size={17} className="text-accent"/><p className="mt-3 text-[10px] text-muted-ink">Order request</p><strong className="text-xs">Received</strong></div><div className="rounded-2xl bg-primary p-3 text-white shadow-sm"><Icon name="headset" size={17}/><p className="mt-3 text-[10px] text-white/65">New message</p><strong className="text-xs">Supplier chat</strong></div></div></div></div>}
