"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { CAMBODIA_PROVINCES, PRODUCT_CATEGORIES, validateCambodianPhone } from "@/lib/cambodia";
import { getAccountByGmail, type RegistrationProfile } from "@/lib/localStorage";
import { homeForRole, useAuth } from "./AuthProvider";

const initial={role:"customer" as "customer"|"supplier",fullName:"",gender:"",businessName:"",gmail:"",phoneNumber:"",nationalId:"",province:"",district:"",commune:"",addressDetails:"",businessCategory:"",businessDescription:"",businessAddressDetails:"",profileImageUrl:"",businessLogoUrl:""};
export function LoginForm(){const router=useRouter(),{login}=useAuth();const [form,setForm]=useState(initial),[code,setCode]=useState(""),[entered,setEntered]=useState(""),[phoneVerified,setVerified]=useState(false),[terms,setTerms]=useState(false),[accurate,setAccurate]=useState(false),[error,setError]=useState("");const existing=getAccountByGmail(form.gmail);
 const update=(name:keyof typeof form,value:string)=>{setForm({...form,[name]:value});setError("");if(name==="phoneNumber")setVerified(false)};
 const sendCode=()=>{if(!validateCambodianPhone(form.phoneNumber)){setError("Enter a valid Cambodian phone number.");return}setCode(String(Math.floor(100000+Math.random()*900000)));setEntered("");setVerified(false);setError("")};
 const verify=()=>{if(entered===code&&code.length===6){setVerified(true);setError("")}else setError("The verification code does not match.")};
 const submit=(e:FormEvent)=>{e.preventDefault();setError("");try{let profile:RegistrationProfile|undefined;if(!existing&&form.gmail.trim().toLowerCase()!=="admin@gmail.com"){if(!terms||!accurate)throw Error("Agree to the Terms and Privacy and confirm your information.");profile={...form,phoneVerified,nationalId:form.nationalId,role:form.role,businessAddressDetails:form.businessAddressDetails||form.addressDetails}}const u=login(form.gmail,profile);router.replace(homeForRole(u.role))}catch(x){setError(x instanceof Error?x.message:"Unable to continue.")}};
 return <div className="w-full max-w-2xl"><span className="eyebrow">Secure Registration</span><h1 className="mt-4 text-3xl font-black">Your verified marketplace account</h1><p className="mt-2 text-sm leading-6 text-muted-ink">Sign in with an existing Gmail or complete identity and phone verification to register.</p><form onSubmit={submit} className="mt-7 space-y-5">
 <Field label="Gmail *"><input type="email" value={form.gmail} onChange={e=>update("gmail",e.target.value)} className="form-control" placeholder="yourname@gmail.com"/></Field>
 {existing||form.gmail.trim().toLowerCase()==="admin@gmail.com"?<div className="notice"><strong>Verified Account found</strong><p className="mt-1 text-xs">Continue to sign in with this Gmail. No password is used in this version.</p></div>:<>
 <div className="grid grid-cols-2 gap-3"><Role active={form.role==="customer"} onClick={()=>update("role","customer")} title="Register as Customer"/><Role active={form.role==="supplier"} onClick={()=>update("role","supplier")} title="Register as Supplier"/></div>
 <div className="grid gap-4 sm:grid-cols-2"><Field label={form.role==="supplier"?"Owner full name *":"Full name *"}><input value={form.fullName} onChange={e=>update("fullName",e.target.value)} className="form-control"/></Field>{form.role==="customer"&&<Field label="Gender (optional)"><select value={form.gender||""} onChange={e=>update("gender" as keyof typeof form,e.target.value)} className="form-control"><option value="">Prefer not to say</option><option>Female</option><option>Male</option><option>Other</option></select></Field>}</div>
 {form.role==="supplier"&&<><div className="grid gap-4 sm:grid-cols-2"><Field label="Business name *"><input value={form.businessName} onChange={e=>update("businessName",e.target.value)} className="form-control"/></Field><Field label="Business category *"><select value={form.businessCategory} onChange={e=>update("businessCategory",e.target.value)} className="form-control"><option value="">Select category</option>{PRODUCT_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="Business description *"><textarea rows={3} value={form.businessDescription} onChange={e=>update("businessDescription",e.target.value)} className="form-control py-3"/></Field></>}
 <div className="rounded-2xl border border-line p-4"><Field label="Cambodian phone number *"><input value={form.phoneNumber} onChange={e=>update("phoneNumber",e.target.value)} className="form-control" placeholder="0XXXXXXXX or +855XXXXXXXX"/><small className="mt-1 block text-muted-ink">Use your active Cambodian phone number.</small></Field><button type="button" onClick={sendCode} className="secondary-btn mt-3">Send Verification Code</button>{code&&<div className="mt-4 rounded-xl bg-primary-soft p-4"><strong>Verification Code: {code}</strong><p className="mt-1 text-xs leading-5 text-muted-ink">SMS delivery is not connected yet. Use the displayed verification code to complete phone verification.</p><div className="mt-3 flex gap-2"><input value={entered} onChange={e=>setEntered(e.target.value.replace(/\D/g,"").slice(0,6))} className="form-control mt-0" placeholder="6-digit code"/><button type="button" onClick={verify} className="primary-btn whitespace-nowrap">Verify phone</button></div></div>}{phoneVerified&&<p className="mt-3 text-sm font-bold text-primary">✓ Phone Verified</p>}</div>
 <Field label={form.role==="supplier"?"Owner National ID number *":"National ID number *"}><input value={form.nationalId} onChange={e=>update("nationalId",e.target.value)} className="form-control"/><small className="mt-2 block leading-5 text-muted-ink">For your privacy, MATRIX SUPPLY Cambodia stores only a masked version of your National ID number in this version.</small></Field>
 <div className="grid gap-4 sm:grid-cols-2"><Field label={form.role==="supplier"?"Business province / city *":"Province / City *"}><select value={form.province} onChange={e=>update("province",e.target.value)} className="form-control"><option value="">Select province / city</option>{CAMBODIA_PROVINCES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="District / Khan (optional)"><input value={form.district} onChange={e=>update("district",e.target.value)} className="form-control"/></Field><Field label="Commune / Sangkat (optional)"><input value={form.commune} onChange={e=>update("commune",e.target.value)} className="form-control"/></Field><Field label={form.role==="supplier"?"Business address details *":"Address details (optional)"}><input value={form.role==="supplier"?form.businessAddressDetails:form.addressDetails} onChange={e=>update(form.role==="supplier"?"businessAddressDetails":"addressDetails",e.target.value)} className="form-control"/></Field></div>
 <Field label={form.role==="supplier"?"Business logo URL (optional)":"Profile photo URL (optional)"}><input value={form.role==="supplier"?form.businessLogoUrl:form.profileImageUrl} onChange={e=>update(form.role==="supplier"?"businessLogoUrl":"profileImageUrl",e.target.value)} className="form-control"/><small className="mt-1 block text-muted-ink">Do not provide a National ID image or sensitive document photo.</small></Field>
 <label className="check-row"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/> I agree to the Terms and Privacy.</label><label className="check-row"><input type="checkbox" checked={accurate} onChange={e=>setAccurate(e.target.checked)}/> I confirm this information is accurate.</label></>}
 {error&&<p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<button className="primary-btn w-full py-3.5">{existing?"Login to Verified Account":"Complete Secure Registration"}</button></form><p className="mt-5 text-center text-xs text-muted-ink">Administrator Gmail: <strong>admin@gmail.com</strong></p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-semibold">{label}{children}</label>}
function Role({active,onClick,title}:{active:boolean;onClick:()=>void;title:string}){return <button type="button" onClick={onClick} className={`rounded-xl border p-4 text-left text-sm font-bold ${active?"border-primary bg-primary-soft text-primary":"border-line"}`}>{title}</button>}
