"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getNotifications, markNotificationRead, PLATFORM_CHANGED_EVENT, type Notification } from "@/lib/localStorage";
import { useAuth } from "./AuthProvider";
import { EmptyState, PageHeader } from "./ui";
import { Icon } from "./Icon";
const icons:Record<Notification["type"],"cart"|"headset"|"package"|"shield"|"user">={order:"cart",chat:"headset",product:"package",system:"shield",report:"shield",account:"user"};
export function NotificationsView(){const {user}=useAuth(),[items,setItems]=useState<Notification[]>([]);useEffect(()=>{if(!user)return;const sync=()=>setItems(getNotifications(user.id));sync();window.addEventListener(PLATFORM_CHANGED_EVENT,sync);window.addEventListener("storage",sync);return()=>{window.removeEventListener(PLATFORM_CHANGED_EVENT,sync);window.removeEventListener("storage",sync)}},[user]);if(!user)return null;const unread=items.filter(n=>!n.read).length;const markAll=()=>{items.filter(n=>!n.read).forEach(n=>markNotificationRead(n.id))};return <div className="container-shell page-pad"><PageHeader eyebrow="Platform Activity" title="Notifications" description="Order, chat, product, account, and marketplace safety updates in one place." actions={unread>0?<button onClick={markAll} className="secondary-btn">Mark all as read</button>:undefined}/>{items.length?<div className="card divide-y divide-line overflow-hidden">{items.map(n=><article key={n.id} className={`flex gap-4 p-5 transition ${!n.read?"bg-primary-soft/45":"bg-white"}`}><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${!n.read?"bg-primary text-white":"bg-slate-100 text-slate-500"}`}><Icon name={icons[n.type]} size={18}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">{n.title}</h2><span className="text-[11px] text-muted-ink">{new Date(n.createdAt).toLocaleString()}</span></div><p className="mt-1 text-sm leading-6 text-muted-ink">{n.message}</p><div className="mt-3 flex items-center gap-4">{n.link&&<Link href={n.link} className="text-xs font-bold text-primary">Open activity →</Link>}{!n.read&&<button onClick={()=>markNotificationRead(n.id)} className="text-xs font-bold text-accent">Mark as read</button>}</div></div>{!n.read&&<span className="mt-2 size-2 shrink-0 rounded-full bg-accent"/>}</article>)}</div>:<EmptyState icon="package" title="No notifications yet" description="Updates about orders, chats, products, and account activity will appear here." actionLabel="Browse Marketplace" href="/products"/>}</div>}
