import Link from "next/link";
import { Icon } from "@/components/Icon";
import { PageShell } from "@/components/PageShell";
import { orders } from "@/lib/data";

export default function AccountPage() {
  return <PageShell><div className="bg-[#f8faf9]"><div className="container-shell page-pad"><p className="text-sm text-muted-ink">Home <span className="mx-2">›</span> Account</p><div className="mt-5 flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><span className="grid size-16 place-items-center rounded-2xl bg-primary text-2xl font-bold text-white">SN</span><div><h1 className="text-3xl font-black">Sophea Nhem</h1><p className="text-sm text-muted-ink">sophea@example.com · Member since 2024</p></div></div><Link href="/login" className="rounded-xl border border-line bg-white px-4 py-2.5 text-sm font-semibold">Sign out</Link></div><div className="mt-8 grid gap-6 lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="surface-card h-fit p-3">{[["user", "Profile"], ["mapPin", "Addresses"], ["creditCard", "Payments"], ["heart", "Saved items"], ["shield", "Security"]].map(([icon, label], index) => <button key={label} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium ${index === 0 ? "bg-primary-soft text-primary" : "text-muted-ink hover:bg-[#f6f8f7]"}`}><Icon name={icon as "user"} size={18}/>{label}</button>)}</aside><div className="space-y-6"><section className="surface-card p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Profile details</h2><button className="text-sm font-semibold text-primary">Edit profile</button></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Info label="Full name" value="Sophea Nhem"/><Info label="Email" value="sophea@example.com"/><Info label="Phone" value="+855 12 345 678"/><Info label="Preferred language" value="English"/></div></section><section className="surface-card p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Recent orders</h2><Link href="/orders" className="text-sm font-semibold text-primary">View all →</Link></div><div className="mt-5 divide-y divide-line">{orders.slice(0, 3).map((order) => <div key={order.id} className="flex flex-col justify-between gap-3 py-4 first:pt-0 sm:flex-row sm:items-center"><div><strong className="text-sm">{order.id}</strong><p className="text-xs text-muted-ink">{order.date} · {order.items} items</p></div><div className="flex items-center gap-5"><span className="rounded-full bg-primary-soft px-3 py-1 text-xs font-semibold text-primary">{order.status}</span><strong>${order.total.toFixed(2)}</strong></div></div>)}</div></section></div></div></div></div></PageShell>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><span className="text-xs font-medium text-muted-ink">{label}</span><p className="mt-1 rounded-xl border border-line bg-[#f8faf9] px-4 py-3 text-sm">{value}</p></div>; }
